# Generated by Django 2.2.2 on 2019-06-07 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('info_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.Info')),
                ('meeting_room', models.CharField(choices=[(1, 'T0'), (2, 'A0'), (3, 'A1')], max_length=10)),
            ],
            bases=('operations.info',),
        ),
    ]
