# Generated by Django 2.2.2 on 2019-06-07 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('info_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.Info')),
                ('leave_type', models.CharField(choices=[('F', 'FULLDAY'), ('HL', 'HALFDAY'), ('H', 'HOURS')], max_length=10)),
                ('reason', models.CharField(max_length=100)),
                ('supervisor_email', models.EmailField(max_length=254)),
                ('team_lead_email', models.EmailField(max_length=254)),
                ('no_of_days', models.IntegerField()),
            ],
            bases=('operations.info',),
        ),
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('info_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.Info')),
                ('need', models.CharField(choices=[('T', 'TEA'), ('C', 'COFFEE')], max_length=10)),
                ('sugar', models.CharField(choices=[('S', 'SUGAR'), ('N', 'NOSUGAR')], max_length=10)),
            ],
            bases=('operations.info',),
        ),
    ]
